[2025-02-15T21:02:15.935+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-15T21:02:15.958+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prueba_simple.enviar_email scheduled__2025-02-15T20:01:00+00:00 [queued]>
[2025-02-15T21:02:15.969+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prueba_simple.enviar_email scheduled__2025-02-15T20:01:00+00:00 [queued]>
[2025-02-15T21:02:15.969+0100] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-15T21:02:15.990+0100] {taskinstance.py:2890} INFO - Executing <Task(EmailOperator): enviar_email> on 2025-02-15 20:01:00+00:00
[2025-02-15T21:02:15.994+0100] {standard_task_runner.py:72} INFO - Started process 3447 to run task
[2025-02-15T21:02:15.998+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'prueba_simple', 'enviar_email', 'scheduled__2025-02-15T20:01:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpe9l1pe1m']
[2025-02-15T21:02:16.001+0100] {standard_task_runner.py:105} INFO - Job 17: Subtask enviar_email
[2025-02-15T21:02:16.046+0100] {task_command.py:467} INFO - Running <TaskInstance: prueba_simple.enviar_email scheduled__2025-02-15T20:01:00+00:00 [running]> on host n97
[2025-02-15T21:02:16.132+0100] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='prueba_simple' AIRFLOW_CTX_TASK_ID='enviar_email' AIRFLOW_CTX_EXECUTION_DATE='2025-02-15T20:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-15T20:01:00+00:00'
[2025-02-15T21:02:16.133+0100] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-15T21:02:16.163+0100] {logging_mixin.py:190} WARNING - /home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/email.py:155 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-02-15T21:02:16.163+0100] {email.py:272} INFO - Email alerting: attempt 1
[2025-02-15T21:02:26.989+0100] {email.py:283} INFO - Sent an alert email to ['estudiosplateau49@gmail.com']
[2025-02-15T21:02:28.227+0100] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-15T21:02:28.228+0100] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=prueba_simple, task_id=enviar_email, run_id=scheduled__2025-02-15T20:01:00+00:00, execution_date=20250215T200100, start_date=20250215T200215, end_date=20250215T200228
[2025-02-15T21:02:28.275+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-15T21:02:28.288+0100] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-15T21:02:28.289+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
